// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB2nu5P8TSLP-pnwBcEnXp3Wl0GlL6ZW5M',
    appId: '1:892431815654:web:2ea722e307105d77b8bc27',
    messagingSenderId: '892431815654',
    projectId: 'quickr-f979e',
    authDomain: 'quickr-f979e.firebaseapp.com',
    storageBucket: 'quickr-f979e.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaY6msbRsGySQi7klNmmhDmM9kLDOP7Wo',
    appId: '1:892431815654:android:9ae544ef60256bb5b8bc27',
    messagingSenderId: '892431815654',
    projectId: 'quickr-f979e',
    storageBucket: 'quickr-f979e.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBYRxfIxAkfHirT5j9rbfeQDwR43yN0hNg',
    appId: '1:892431815654:ios:8313a3950c569246b8bc27',
    messagingSenderId: '892431815654',
    projectId: 'quickr-f979e',
    storageBucket: 'quickr-f979e.firebasestorage.app',
    iosBundleId: 'com.example.quickr',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBYRxfIxAkfHirT5j9rbfeQDwR43yN0hNg',
    appId: '1:892431815654:ios:8313a3950c569246b8bc27',
    messagingSenderId: '892431815654',
    projectId: 'quickr-f979e',
    storageBucket: 'quickr-f979e.firebasestorage.app',
    iosBundleId: 'com.example.quickr',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyB2nu5P8TSLP-pnwBcEnXp3Wl0GlL6ZW5M',
    appId: '1:892431815654:web:8204bd794b5c294cb8bc27',
    messagingSenderId: '892431815654',
    projectId: 'quickr-f979e',
    authDomain: 'quickr-f979e.firebaseapp.com',
    storageBucket: 'quickr-f979e.firebasestorage.app',
  );
}
